version: '3.8'

services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./spending-tracker-volume:/var/lib/postgresql/data
    networks:
      - spending_tracker_network

networks:
  spending_tracker_network:
    driver: bridge
volumes:
  spending-tracker-volume: